[package]

# Package
name = "secs-test"
version = "0.1.0"
publish = false

# Rust
edition = "2021"
rust-version = "1.82"


[dependencies]

# semi_e5 is MIT
#semi_e5 = "0.2.0"
semi_e5 = {path = "../semi_e5"}

# semi_e37 is MIT
#semi_e37 = "0.2.0"
semi_e37 = {path = "../semi_e37"}
