[package]
name = "secs-test"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]

# semi_e5 is MIT
semi_e5 = "0.2.0"
#semi_e5 = {path = "../semi_e5"}

# semi_e37 is MIT
semi_e37 = "0.2.0"
#semi_e37 = {path = "../semi_e37"}
